baseURL = "https://gsh25.github.io/"
languageCode = "en-us"
title = "SRE Blog!"
theme = "archie"
paginate = 5 
Copyright = "© 2023 gsh25"
canonifyurls = true
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode = "toggle"
	useCDN = false
	subtitle = "All things about SRE, System Design and Security!"
	mathjax = true
	katex = true
        favicon = "/favicon-16x16.png"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/gsh25"

[[menu.main]]
name = "Home"
weight = 1
identifier = "home"
pre = "<br />"
url = "/"

[[menu.main]]
name = "Posts"
weight = 2 
identifier = "posts"
pre = "<br />"
url = "/posts"

[[menu.main]]
name = "Tags"
weight = 3 
identifier = "tags"
pre = "<br />"
url = "/tags"


[[menu.main]]
name = "About"
weight = 4 
identifier = "about"
pre = "<br />"
url = "/about"

